### ISSUE TITLE
Branch to public the docs

### ISSUE THREAD

**Issue by qaqland** [axionl/the_wayland_protocol_zh_CN#1]
From now on, I have free time to do work :)   

Can u use other branch to public the `docs/`? Now the git makes me uncomfortable.

祝好。

**Comment by qaqland** [comment]
啊这，又改回去了，sad，我本地测试都挺正常的

我看你第二次 action 都正常了

X_X

**Comment by axionl** [comment]
> 啊这，又改回去了，sad，我本地测试都挺正常的
> 
> 我看你第二次 action 都正常了
> 
> X_X

就没能用过，我是不明白为什么一个这么简单的 mdbook build 还要用到 jekyll 来构建，可能那个 actions 也不是我想要的 actions

**Comment by qaqland** [comment]
可是 actions 里面就没有 jekyll 

这是我 fork 的 https://github.com/qaqland/the_wayland_protocol_zh_CN
这是我的 action 第一次不知道为啥也出现 jekyll [失败](https://github.com/qaqland/the_wayland_protocol_zh_CN/actions/runs/2201298124) 第二次就 [成功](https://github.com/qaqland/the_wayland_protocol_zh_CN/actions/runs/2201301585)了

最后这是网站 https://qaqland.github.io/the_wayland_protocol_zh_CN/

**Comment by qaqland** [comment]
经过我的测试，我知道了。
在默认没有action的时候，系统会尝试调用内置的 jekyll-action
